2018-03-01 22:39:17,310 INFO: GUI: Generación de Universos de Interventoría
2018-03-01 22:39:17,311 INFO: Getting data from db
2018-03-01 22:39:17,366 INFO: File db/data/reclamos.csv loaded
2018-03-01 22:39:17,893 INFO: File db/data/anomalect.csv loaded
2018-03-01 22:39:18,147 INFO: File db/data/anomafact.csv loaded
2018-03-01 22:39:18,147 INFO: Data wrangling
2018-03-01 22:39:18,231 INFO: unique NIS filter
2018-03-01 22:39:18,235 INFO: Reclamos filter applied
2018-03-01 22:39:18,253 INFO: Field ORIGEN processed
2018-03-01 22:39:18,254 INFO: Field DESCRIPCION added
2018-03-01 22:39:18,256 INFO: Field PROCESO processed
2018-03-01 22:39:18,259 INFO: Field PENULTIMA_LECTURA added
2018-03-01 22:39:18,260 INFO: Field TIPOEQUIPO added
2018-03-01 22:39:19,632 INFO: Added LAT, LON and DELEGACION fields
2018-03-01 22:39:19,634 INFO: Cabeceras filter
2018-03-01 22:39:19,637 INFO: unique NIF filter
2018-03-01 22:39:19,649 INFO: Field ASOCIADO_COMERCIAL processed
2018-03-01 22:39:19,650 INFO: NOM_CLIENTE processed
2018-03-01 22:39:19,652 INFO: Columns sorted
2018-03-01 22:39:19,661 INFO: Universe generation
2018-03-01 22:39:19,674 ERROR: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    gui.universe_generation(data, cfg)
  File "/Users/jonate/Google Drive/Projects/crowis/gui/gui.py", line 136, in universe_generation
    dd = selection(dd, workday, wd, ud)
  File "/Users/jonate/Google Drive/Projects/crowis/gui/gui.py", line 246, in selection
    rpos = np.random.choice(len(pw), ud, replace=False)
  File "mtrand.pyx", line 1192, in mtrand.RandomState.choice
TypeError: 'numpy.float64' object cannot be interpreted as an integer
